"""Static American first/last name and street-address pools for local identity generation.

Pools are deliberately large: the generator never repeats a full name that already exists
in the database, so the number of distinct identities available is first x last.
"""

FIRST_NAMES = [
    "James", "Mary", "Robert", "Patricia", "John", "Jennifer", "Michael", "Linda",
    "David", "Elizabeth", "William", "Barbara", "Richard", "Susan", "Joseph", "Jessica",
    "Thomas", "Sarah", "Christopher", "Karen", "Charles", "Lisa", "Daniel", "Nancy",
    "Matthew", "Betty", "Anthony", "Margaret", "Mark", "Sandra", "Donald", "Ashley",
    "Steven", "Dorothy", "Paul", "Kimberly", "Andrew", "Emily", "Joshua", "Donna",
    "Kenneth", "Michelle", "Kevin", "Carol", "Brian", "Amanda", "George", "Melissa",
    "Timothy", "Deborah", "Ronald", "Stephanie", "Edward", "Rebecca", "Jason", "Sharon",
    "Jeffrey", "Laura", "Ryan", "Cynthia", "Jacob", "Kathleen", "Gary", "Amy",
    "Nicholas", "Angela", "Eric", "Shirley", "Jonathan", "Anna", "Stephen", "Brenda",
    "Larry", "Pamela", "Justin", "Emma", "Scott", "Nicole", "Brandon", "Helen",
    "Benjamin", "Samantha", "Samuel", "Katherine", "Raymond", "Christine", "Gregory", "Debra",
    "Frank", "Rachel", "Alexander", "Carolyn", "Patrick", "Janet", "Jack", "Catherine",
    "Dennis", "Maria", "Jerry", "Heather", "Tyler", "Diane", "Aaron", "Ruth",
    "Nathan", "Megan", "Henry", "Andrea", "Douglas", "Cheryl", "Peter", "Jacqueline",
    "Adam", "Hannah", "Zachary", "Olivia", "Harold", "Gloria", "Kyle", "Teresa",
    "Carl", "Sara", "Arthur", "Janice", "Gerald", "Jean", "Roger", "Abigail",
    "Lawrence", "Alice", "Jesse", "Judy", "Dylan", "Sophia", "Bryan", "Grace",
    "Jordan", "Amber", "Bruce", "Marilyn", "Gabriel", "Isabella", "Logan", "Theresa",
    "Alan", "Diana", "Juan", "Natalie", "Wayne", "Brittany", "Elijah", "Charlotte",
    "Randy", "Marie", "Roy", "Kayla", "Vincent", "Alexis", "Ralph", "Lori",
    "Noah", "Lily", "Liam", "Ella", "Owen", "Nora", "Caleb", "Hazel",
    "Luke", "Violet", "Isaac", "Aurora", "Landon", "Savannah", "Adrian", "Stella",
    "Connor", "Lucy", "Carson", "Paisley", "Miles", "Skylar", "Cooper", "Maya",
    "Colton", "Brianna", "Damian", "Camila", "Everett", "Sienna", "Graham", "Delilah",
    "Hudson", "Josephine", "Ian", "Elena", "Jasper", "Adeline", "Leo", "Vivian",
    "Malcolm", "Rosalie", "Nolan", "Clara", "Preston", "Ivy", "Quinn", "Juliette",
    "Roman", "Bianca", "Sawyer", "Marisol", "Tobias", "Celeste", "Victor", "Naomi",
    "Weston", "Priya", "Xavier", "Simone", "Emmett", "Freya", "Desmond", "Talia",
    "Julian", "Ophelia", "Marcus", "Eliza", "Sterling", "Rowan", "Beckett", "Wren",
    "Callum", "Sloane", "Dashiell", "Margot", "Ellis", "Noelle", "Finn", "Camille",
    "Grady", "Imani", "Hayes", "Jocelyn", "Kai", "Leilani", "Lucian", "Mabel",
    "Ezra", "Corinne", "Reid", "Tessa", "Rafael", "Anika", "Simon", "Marguerite",
]

LAST_NAMES = [
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis",
    "Rodriguez", "Martinez", "Hernandez", "Lopez", "Gonzalez", "Wilson", "Anderson",
    "Thomas", "Taylor", "Moore", "Jackson", "Martin", "Lee", "Perez", "Thompson",
    "White", "Harris", "Sanchez", "Clark", "Ramirez", "Lewis", "Robinson", "Walker",
    "Young", "Allen", "King", "Wright", "Scott", "Torres", "Nguyen", "Hill",
    "Flores", "Green", "Adams", "Nelson", "Baker", "Hall", "Rivera", "Campbell",
    "Mitchell", "Carter", "Roberts", "Gomez", "Phillips", "Evans", "Turner", "Diaz",
    "Parker", "Cruz", "Edwards", "Collins", "Reyes", "Stewart", "Morris", "Morales",
    "Murphy", "Cook", "Rogers", "Gutierrez", "Ortiz", "Morgan", "Cooper", "Peterson",
    "Bailey", "Reed", "Kelly", "Howard", "Ramos", "Kim", "Cox", "Ward",
    "Richardson", "Watson", "Brooks", "Chavez", "Wood", "James", "Bennett", "Gray",
    "Mendoza", "Ruiz", "Hughes", "Price", "Alvarez", "Castillo", "Sanders", "Patel",
    "Myers", "Long", "Ross", "Foster", "Jimenez", "Powell",
    "Sullivan", "Russell", "Ortega", "Jenkins", "Medina", "Vargas", "Olson", "Freeman",
    "Hart", "Burns", "Stone", "Fox", "Webb", "Burke", "Spencer", "Steele",
    "Keller", "Dunn", "Curry", "Fitzgerald", "Vasquez", "Hicks", "Moran", "Garza",
    "Delgado", "Bates", "Bishop", "Daniel", "Herrera", "Lindsey", "Vaughn",
    "Haynes", "Frost", "Lambert", "Drake", "Bowers", "Nash", "Barber", "Watts",
    "Lyons", "Harmon", "Maxwell", "Vega", "Malone", "Caldwell", "Durham",
    "Payne", "Wolfe", "Benson", "Klein", "Swanson", "Hodges", "Barton", "Schroeder",
    "Abbott", "Ballard", "Beltran", "Blackwell", "Bradshaw", "Cabrera", "Cannon",
    "Christensen", "Colon", "Conway", "Dalton", "Dawson", "Dickerson", "Donovan",
    "Duffy", "Escobar", "Farley", "Ferguson", "Fleming", "Franco", "Gallagher",
    "Gibbs", "Glover", "Goodwin", "Guerrero", "Hampton", "Hansen", "Hoffman",
    "Holloway", "Ingram", "Jarvis", "Kaufman", "Kirby", "Langley", "Leonard",
    "Lozano", "Mackenzie", "Marsh", "McBride", "Mercado", "Middleton", "Monroe",
    "Nolan", "Norris", "Osborne", "Pace", "Pratt", "Quinn", "Rasmussen", "Rhodes",
    "Rivas", "Salazar", "Sawyer", "Sheppard", "Solis", "Stanton", "Sweeney",
    "Tanner", "Thornton", "Trevino", "Underwood", "Valentine", "Villarreal",
    "Wagner", "Walsh", "Whitaker", "Winters", "Yates", "Zamora",
]

STREET_ADDRESSES = [
    "102 Maple Ave", "215 Oak St", "331 Cedar Ln", "447 Pine Rd", "508 Elm Dr",
    "619 Birch Way", "724 Walnut Ct", "830 Spruce Blvd", "945 Willow Pl", "101 Cherry St",
    "213 Ash Ave", "327 Poplar Ln", "432 Hickory Rd", "546 Magnolia Dr", "651 Cypress Way",
    "768 Juniper Ct", "874 Sycamore Blvd", "982 Redwood Pl", "104 Chestnut St",
    "218 Laurel Ave", "325 Dogwood Ln", "439 Hawthorn Rd", "543 Alder Dr", "658 Beech Way",
    "761 Fir Ct", "877 Holly Blvd", "993 Ivy Pl", "106 Pecan St", "220 Locust Ave",
    "334 Mulberry Ln", "1420 Washington Blvd", "2835 Lincoln Ave", "3901 Jefferson St",
    "4215 Madison Dr", "5108 Adams Rd", "6322 Monroe Way", "7430 Jackson Ct",
    "8544 Harrison Pl", "9617 Tyler Blvd", "1025 Polk St", "2139 Taylor Ave",
    "3243 Fillmore Ln", "4357 Pierce Rd", "5461 Buchanan Dr", "6575 Grant Way",
    "7689 Hayes Ct", "8793 Garfield Pl", "9807 Arthur Blvd", "1134 Cleveland St",
    "2248 McKinley Ave", "3362 Roosevelt Ln", "4476 Taft Rd", "5580 Wilson Dr",
    "6694 Harding Way", "7708 Coolidge Ct", "8812 Hoover Pl", "9926 Truman Blvd",
    "1041 Eisenhower St", "2155 Kennedy Ave", "3269 Nixon Ln", "4373 Ford Rd",
    "5487 Carter Dr", "6591 Reagan Way", "110 Park Ave", "225 Broadway", "340 Main St",
    "455 Market St", "570 Central Ave", "685 Church St", "800 School Rd", "915 Water St",
    "1030 Bridge Ln", "1145 Mill Rd", "1260 River Dr", "1375 Lake Way", "1490 Hill Ct",
    "1505 Valley Blvd", "1620 Spring Pl", "1735 Meadow St", "1850 Forest Ave",
    "1965 Ridge Ln", "2080 Sunset Rd", "2195 Highland Dr", "2310 Garden Way",
    "2425 Grove Ct", "2540 North Blvd", "2655 South Pl", "2770 East St", "2885 West Ave",
    "3000 College Ln", "3115 Academy Rd", "3230 Liberty Dr", "3345 Union Way",
    "3460 Railroad Ct", "3575 Commerce Blvd", "3690 Division Pl", "3805 Prospect St",
    "3920 Summit Ave", "4035 Center Ln", "4150 Court Rd", "4265 Pleasant Dr",
    "504 Greenfield Rd", "609 Brookside Dr", "714 Lakeview Ave", "819 Riverview St",
    "924 Hillside Ln", "1029 Fairview Rd", "1134 Grandview Dr", "1239 Clearview Ave",
    "1344 Northfield St", "1449 Southgate Ln", "1554 Eastwood Rd", "1659 Westgate Dr",
    "1764 Lakewood Ave", "1869 Parkview St", "1974 Ridgewood Ln", "2079 Woodland Rd",
    "2184 Foxhill Dr", "2289 Stonegate Ave", "2394 Creekside St", "2499 Bayview Ln",
    "401 Orchard Rd", "516 Vineyard Dr", "631 Harvest Ave", "746 Fieldstone St",
    "861 Cobblestone Ln", "976 Pebble Creek Rd", "1091 Silver Oak Dr",
    "1206 Golden Gate Ave", "1321 Iron Horse St", "1436 Copper Ridge Ln",
    "1551 Bronze Way Rd", "1666 Platinum Dr", "1781 Diamond Ave", "1896 Emerald St",
    "2011 Ruby Ln", "2126 Sapphire Rd", "312 Falcon Ct", "427 Eagle Dr", "542 Hawk Ave",
    "657 Osprey St", "772 Robin Ln", "887 Cardinal Rd", "1002 Blue Jay Dr", "1117 Wren Ave",
    "1232 Finch St", "1347 Dove Ln", "1462 Sparrow Rd", "1577 Pelican Dr", "1692 Heron Ave",
    "1807 Crane St", "1922 Lark Ln", "2037 Oriole Rd", "2152 Tanager Dr", "2267 Thrush Ave",
    "2382 Warbler St", "2497 Swift Ln", "408 Sunrise Blvd", "523 Sunset Way",
    "638 Moonlight Dr", "753 Starlight Ave", "868 Twilight St", "983 Dawn Ln",
    "1098 Dusk Rd", "1213 Aurora Dr", "1328 Eclipse Ave", "1443 Horizon St",
    "1558 Skyline Ln", "1673 Summit Rd", "1788 Vista Dr", "1903 Panorama Ave",
    "2018 Overlook St", "2133 Canyon Ln", "2248 Bluff Rd", "2363 Terrace Dr",
    "2478 Mesa Ave", "2593 Plateau St", "2708 Basin Ln", "2823 Delta Rd",
    "2938 Prairie Dr", "3053 Savanna Ave", "3168 Timber St", "3283 Boulder Ln",
    "3398 Granite Rd", "3513 Marble Dr", "3628 Slate Ave", "3743 Sandstone St",
    "3858 Limestone Ln", "3973 Quarry Rd", "4088 Flint Dr", "4203 Aspen Ave",
    "4318 Sequoia St",
]
